name: Excollab-Manager

on:
  push:
    paths:
      - 'manager/*'
    branches: [ master ]
  pull_request:
    paths:
      - 'manager/*'
    branches: [ master ]

jobs:
  buildManageCollab:
    name: Build manage-collab
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: manager

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        id: Build
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Test
        id: Test
        run: npm test

      - uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()


  deployManageCollab:
    name: Deploy manage-collab - Cloud Function
    runs-on: ubuntu-latest
    needs: [buildManageCollab]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GCP
        id: Deploy
        uses: actions-hub/gcloud@307.0.0
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_CREDENTIALS}}
        with:
          args: functions deploy manage-collab --region europe-west2  --runtime nodejs12 --source manager --entry-point manage --trigger-topic ex-collab --retry

      - uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
