runtime: nodejs12
instance_class: F2
service: ex-collab-manager

env_variables:
  PROJECT_ID: stoked-reality-284921
  PUBSUB_TOPIC: ex-collab
  PUBSUB_VERIFICATION_TOKEN: SFwO64g5bLf30B6QPkcfEv7D
  PARENT_ZONE: extream.app
  MACHINE_TYPE: c2-standard-8
  MACHINE_IMAGE: kms