steps:
- name: 'mediaserver-build'
  id: 'Build and Push'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      export DOCKER_BUILDKIT=1 && \
      docker build -f server/Dockerfile -t gcr.io/stoked-reality-284921/excollab-mediaserver:latest --build-arg BUILDKIT_INLINE_CACHE=1 server && \
      docker push gcr.io/stoked-reality-284921/excollab-mediaserver:latest